## Завдання 3 - на R не вийшло, тому моделюю його на пайтоні у іншому файлі
Змоделювати ланцюг Маркова з поглинанням для заданих 
перехідних і початкових ймовірностей (варіант із завдання 1, довжина 
реалізації – до поглинання). Кількість реалізацій – більше 100.
Моделювання ланцюга маркова відбувається за таким алгоритмом:
1. Моделюємо початковий стан – k.
2. Перехід із стану k в наступний регламентує k-й рядок матриці, моделюємо наступний стан - стан k.
3. Якщо необхідно моделювати наступний стан, то переходимо на 2.

Матриця для мого варіанту виглядає так

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

P =  np.array([[1, 0, 0, 0],[0.24, 0.25, 0.42, 0.09],[0.24, 0.05, 0.24, 0.47],[0.13, 0.65, 0.21, 0.01]])
p0 = np.array([0.2,0.1,0.2,0.5])
print(P) 

[[1.   0.   0.   0.  ]
 [0.24 0.25 0.42 0.09]
 [0.24 0.05 0.24 0.47]
 [0.13 0.65 0.21 0.01]]


Обираємо кількість реалізацій

In [2]:
M = int(input('Оберіть кількість реалізацій '))

Допоміжна функція для визначення наступного стану:
- генеруємо випадкове число
- визначаємо для нього стан
- виводимо номер стану

In [3]:
# k_generator <- function(p){
#     r <- runif(1000)[runif(1,1,1000)]
#     curr <- 0
#     for (i in 1:(length(p))){
#         curr <- curr+p[i]
#         if (curr>=r){return (i)}
#     }
# }

def k_generator(p):
    r = np.random.uniform(0, 1)
    curr = 0
    for i, pe in enumerate(p):
        curr += pe
        if curr>=r: 
            return i+1

Почнімо моделювати ланцюг Маркова

Спочатку беремо початковий стан р0 та генеруємо деяке число r. Визначаємо якому стану воно належить та переходимо у нього. Потім "витягаємо" цей стан з нашої матриці ймовірностей та так само генеруємо випадкове число, визначаємо стан та переходимо до нього, допоки не отримаємо одиницю. Повторюємо те саме М-1 разів

In [4]:
stop = 1
lens = []
for m in range(M):
    ktemp = []
    k = k_generator(p0)
    while k!= stop:
        t = P[k-1]
        k = k_generator(t)
        ktemp.append(k)
    lens.append(ktemp)

Для зручної візуалізації скористаємося мовою R

In [5]:
f <- runif(0,1,100)
plot(f)


NameError: name 'f' is not defined