# Лабораторна робота з випадкових процесів №3
                                            Виконала Неділько Дарина КМ-91

## Завдання 1
Для поглинаючого ланцюга Маркова знайти:
- матрицю переходів;
- фундаментальну матрицю;
- середню кількість кроків, яку ланцюг знаходиться в стані коли процес почався зі стану ; 
- середню кількість кроків, яку ланцюг знаходиться в стані j коли початковий стан не заданий;
- середній час поглинання;
- ймовірність поглинання;

## Варіант 8
Для мого варіанту матриця переходу та вектор p0 виглядають так:

In [1]:
pij <- c('p11','p12','p13','p14',0.24,0.25,'p23',0.09,0.24,0.05,0.24,'p34',0.13,'p42',0.21,0.01)
P <- t(matrix(pij,ncol=4))
print(P, quote=FALSE)
p0 <- c(0.2,0.1,0.2,0.5)

     [,1] [,2] [,3] [,4]
[1,] p11  p12  p13  p14 
[2,] 0.24 0.25 p23  0.09
[3,] 0.24 0.05 0.24 p34 
[4,] 0.13 p42  0.21 0.01


Знаходимо невідомі елементи, враховуючи за правило, що сума елементів у кожному ряду = 1. Оскільки це поглинаючий ланцюг, то P[1,1] буде дорівнювати одиниці, а решта елементів рядку - нулю.

In [2]:
P[1,1] <- 1
P[1,2:4] <- 0
for (i in 2:4){
  for (k in 1:4){
    if (is.na(as.numeric(P[i,k]))){
      P[i,k] <- 1-sum(as.numeric(c(P[i,-k])))
    }
  }
}
P <- apply(P,2,as.numeric)
cat('\nNow we got:\n')
print(P)

Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"
Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"
Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"



Now we got:
     [,1] [,2] [,3] [,4]
[1,] 1.00 0.00 0.00 0.00
[2,] 0.24 0.25 0.42 0.09
[3,] 0.24 0.05 0.24 0.47
[4,] 0.13 0.65 0.21 0.01


Знайдена нами матриця переходів знаходиться у канонічній формі. Запишемо для неї матриці I, O, Q та R:

In [3]:
cat('I\n')
I <- print(P[1,1])
cat('\nO\n')
o <- print(P[,2:4])
cat('\nQ\n')
Q <- print(P[2:4,2:4])
cat('\nR\n')
R <- print(P[2:4,1])

I
[1] 1

O
     [,1] [,2] [,3]
[1,] 0.00 0.00 0.00
[2,] 0.25 0.42 0.09
[3,] 0.05 0.24 0.47
[4,] 0.65 0.21 0.01

Q
     [,1] [,2] [,3]
[1,] 0.25 0.42 0.09
[2,] 0.05 0.24 0.47
[3,] 0.65 0.21 0.01

R
[1] 0.24 0.24 0.13


Щоб знайти фундаментальну матрицю будемо використовувати формулу 
$N=(I-Q)^{-1}$. Для початку знайдемо матрицю I-Q:

In [4]:
Im <-print(matrix(c(1,0,0,0),3,3))

ImQ <- print(Im-Q)

Warning message in matrix(c(1, 0, 0, 0), 3, 3):
"data length [4] is not a sub-multiple or multiple of the number of rows [3]"


     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1
      [,1]  [,2]  [,3]
[1,]  0.75 -0.42 -0.09
[2,] -0.05  0.76 -0.47
[3,] -0.65 -0.21  0.99


Тепер знаходимо обернену до цієї

In [5]:
cat('N=\n')
N <- print(solve(ImQ))

N=
         [,1]     [,2]      [,3]
[1,] 2.210163 1.469723 0.8986713
[2,] 1.200257 2.312608 1.2070190
[3,] 1.705717 1.455523 1.8561720


Середня кількість кроків, яку ланцюг знаходиться у стані j, коли процес почався зі стану і, визначається елементом фундаментальної матриці N, що знаходиться на перетині i-того рядка та j-того стовбчика. Тобто N[i,j]. Виводимо середню кількість кроків i -> j

In [6]:
for (i in 1:3){for (j in 1:3){cat('W',i+1,' -> W',j+1,': ',N[i,j],'\n')}}

W 2  -> W 2 :  2.210163 
W 2  -> W 3 :  1.469723 
W 2  -> W 4 :  0.8986713 
W 3  -> W 2 :  1.200257 
W 3  -> W 3 :  2.312608 
W 3  -> W 4 :  1.207019 
W 4  -> W 2 :  1.705717 
W 4  -> W 3 :  1.455523 
W 4  -> W 4 :  1.856172 


Середня кількість кроків, яку ланцюг знаходиться у стані j, без заданого початку

In [39]:
W <- sapply(1:3,function(x) sum(N[,x])/3)
for (i in 1:3){cat('W',i+1,': ', W[i],'\n')}

W 2 :  1.705379 
W 3 :  1.745951 
W 4 :  1.320621 


Середній час поглинання визначається за формулою $\varsigma = N*\xi$, де $\xi = \begin{matrix}
1\\
1\\
1 
\end{matrix} $

In [40]:
varsig<- print(N%*%matrix(c(1,1,1)))

         [,1]
[1,] 4.578558
[2,] 4.719884
[3,] 5.017412


Ймовірність поглинання шукається за формулою B=N*R

In [41]:
cat("Matrix R:\n")
print(R)
cat("Matrix N:\n")
print(N)
cat("Probability of absorbtion\n")

B <- print(N%*%R)

Matrix R:
[1] 0.24 0.24 0.13
Matrix N:
         [,1]     [,2]      [,3]
[1,] 2.210163 1.469723 0.8986713
[2,] 1.200257 2.312608 1.2070190
[3,] 1.705717 1.455523 1.8561720
Probability of absorbtion
     [,1]
[1,]    1
[2,]    1
[3,]    1


## Завдання 2
Для регулярного ланцюга Маркова знайти: 
- матрицю переходів;
- фінальні ймовірності;
- фундаментальну матрицю;
- середній час перебування в заданому стані за n=4 кроків;
- середній час виходу ланцюга в заданий стан (в стан j, коли процес почався зі стану );
- середній час виходу ланцюга в заданий стан (коли початковий стан не заданий);
- середній час виходу ланцюга в заданий стан в стаціонарному режимі (коли початковий стан не заданий).

Матриця переходів для мого варіанту матиме вигляд:

In [10]:
n <- 4
Pn <- t(matrix(c(0.28,0.41,'p13','p21',0.23,0.48,0.24,'p32',0.35),3))
p0n <- c(0.42,0.14,0.44)
cat("Marix:\n")
print(Pn)
cat("\np0 ->", p0n)


Marix:
     [,1]   [,2]   [,3]  
[1,] "0.28" "0.41" "p13" 
[2,] "p21"  "0.23" "0.48"
[3,] "0.24" "p32"  "0.35"

p0 -> 0.42 0.14 0.44

Оскільки сума елементів у рядку має дорівнювати 1, знаходимо невідомі елементи

In [11]:
for (i in 1:3){
  for (k in 1:3){
    if (is.na(as.numeric(Pn[i,k]))){
      Pn[i,k] <- 1-sum(as.numeric(c(Pn[i,-k])))
    }
  }
}
Pn <- apply(Pn,2, as.numeric)
cat('\nNow we got:\n')
print(Pn)

Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"
Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"
Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"



Now we got:
     [,1] [,2] [,3]
[1,] 0.28 0.41 0.31
[2,] 0.29 0.23 0.48
[3,] 0.24 0.41 0.35


Знайдемо фінальні ймовірності: $\vec{w} = \vec{p_0}*\pi^k $, де k це кількість кроків, за який регулярний процес вийде на стаціонарний режим

In [70]:
powM = function(n, Pn)
 {
    if (n==1){return (Pn)}
    if (n==2){return (Pn%*%Pn)}
    if (n>2){return (Pn%*%powM(n-1,Pn))}
 }


temp <- p0
for (i in 1:100000){
    W <-powM(i,Pn)
    if (all(W[1,]==W[2,],W[2,]==W[3,])){
        cat('K =',i,'regular prosses Markova reach it`s final probabilities')
        break
    }else{
        temp <- W
    }
}

fin <-as.vector(p0n %*% temp)

Матриця фінальних ймовірностей буде мати вигляд:

In [71]:
W <- print(rep(1,3)%*%t.default(fin))

          [,1]      [,2]      [,3]
[1,] 0.2680968 0.3474576 0.3844456
[2,] 0.2680968 0.3474576 0.3844456
[3,] 0.2680968 0.3474576 0.3844456


Фундаментальна матриця шукається за формулою: $ Z=(I-(\pi-W))^{-1}$

Спочатку визначимо матрицю $(\pi-W)$

In [72]:
Z1 <- Pn-W
print(Z1)

            [,1]        [,2]        [,3]
[1,]  0.01190325  0.06254237 -0.07444562
[2,]  0.02190325 -0.11745763  0.09555438
[3,] -0.02809675  0.06254237 -0.03444562


Тепер визначимо матрицю $(I-(\pi-W))$

In [73]:
Z2 <- print(Im-Z1)

            [,1]        [,2]        [,3]
[1,]  0.98809675 -0.06254237  0.07444562
[2,] -0.02190325  1.11745763 -0.09555438
[3,]  0.02809675 -0.06254237  1.03444562


Фундаментальна матриця матиме вигляд

In [74]:
Z <- print(solve(Z2))

            [,1]       [,2]        [,3]
[1,]  1.01515974 0.05300201 -0.06816175
[2,]  0.01763149 0.90045964  0.08190887
[3,] -0.02650693 0.05300201  0.97350492


Знайдемо середній час перебування в заданому стані для n=4
Обрахунок відбувається за формулою $C = n\vec{W}$, де n - кількість кроків

In [75]:
C <- print(4*W[1,])


[1] 1.072387 1.389831 1.537782


Середній час виходу ланцюга в стан j, коли початковий стан почався зі стану n
Це визначається елементом [n,j] матриці М, що визначається:
$ M = (I-Z + E*Z_{dg})*D$, де 
- I - одинична матриця
- Z - фундаментальна матриця
- E - матриця з одиниць
- $Z_{dg}$ - матриця, де на діагоналі елементи фундаментальної матриці
- D - діагональна матриця, елементи якої визначаються як $d_{i,i} = \frac{1}{w_i}$, де $w_i$ - елементи вектору $\vec{W}$

Спочатку знайдемо матрицю $E*Z_{dg}$

In [85]:
Zdg <- matrix(c(Z[1,1],rep(0,3),Z[2,2],rep(0,3),Z[3,3]),3)

EZdg <- print(matrix(1,3,3)%*%Zdg)

        [,1]      [,2]      [,3]
[1,] 1.01516 0.9004596 0.9735049
[2,] 1.01516 0.9004596 0.9735049
[3,] 1.01516 0.9004596 0.9735049


Тепер визначимо матрицю I-Z

In [77]:
IZ <- print(Im - Z)

            [,1]        [,2]        [,3]
[1,] -0.01515974 -0.05300201  0.06816175
[2,] -0.01763149  0.09954036 -0.08190887
[3,]  0.02650693 -0.05300201  0.02649508


Тепер шукаємо матрицю $(I-Z + E*Z_{dg})$

In [78]:
Mk <- print(IZ + EZdg)

          [,1]      [,2]     [,3]
[1,] 1.0000000 0.8474576 1.041667
[2,] 0.9975282 1.0000000 0.891596
[3,] 1.0416667 0.8474576 1.000000


Визначаємо матрицю D = 
$\begin{pmatrix}
  \frac{1}{w_1} & 0 & 0 \\
  0 & \frac{1}{w_2} & 0 \\
  0 & 0 & \frac{1}{w_3}
 \end{pmatrix}$


In [79]:
D <- matrix(c(1/W[1,1],rep(0,3),1/W[2,2],rep(0,3),1/W[3,3]),3)
print(D)

         [,1]     [,2]     [,3]
[1,] 3.729997 0.000000 0.000000
[2,] 0.000000 2.878049 0.000000
[3,] 0.000000 0.000000 2.601148


Тепер знаходимо матрицю $ M = (I-Z + E*Z_{dg})*D$

In [80]:
M <- print(Mk %*% D)

         [,1]     [,2]     [,3]
[1,] 3.729997 2.439024 2.709529
[2,] 3.720777 2.878049 2.319173
[3,] 3.885413 2.439024 2.601148


Середній час виходу ланцюга в стан j зі стану i буде становити:

In [81]:
for (i in 1:3){for (j in 1:3){cat('W',i,' -> W',j,': ',M[i,j],'\n')}}

W 1  -> W 1 :  3.729997 
W 1  -> W 2 :  2.439024 
W 1  -> W 3 :  2.709529 
W 2  -> W 1 :  3.720777 
W 2  -> W 2 :  2.878049 
W 2  -> W 3 :  2.319173 
W 3  -> W 1 :  3.885413 
W 3  -> W 2 :  2.439024 
W 3  -> W 3 :  2.601148 


Тепер визначимо середній час виходу ланцюга в заданий стан, за умови, що початковий стан не задано
Обраховується це як $W_i:(M_{i1} + M_{i2} + M_{i3}):3 $

In [82]:
w1 <- sum(M[1,])/3
w2 <- sum(M[2,])/3 
w3 <- sum(M[3,])/3
Ww <- c(w1,w2,w3)
for (i in 1:3){
    cat("W",i,":", Ww[i],'\n')
}

W 1 : 2.959517 
W 2 : 2.972666 
W 3 : 2.975195 


Дізнаємося середній час виходу ланцюга в заданий стан і стаціонарному режимі, коли початковий стан не вказано. Будемо використовувати формулу $D=\frac{1}{w_i}$

In [83]:
D <- print(sapply(1:3, function(i) 1/(W[1,i])))

[1] 3.729997 2.878049 2.601148


## Завдання 3 - на R не вийшло, тому моделюю його на пайтоні у іншому файлі